# email_sender.py

import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from dotenv import load_dotenv
import os

load_dotenv()

class EmailSender:
    """Send flight deals via email"""
    
    def __init__(self):
        self.sender_email = os.getenv('EMAIL_ADDRESS')
        self.sender_password = os.getenv('EMAIL_PASSWORD')
        self.smtp_server = "smtp.gmail.com"
        self.smtp_port = 587
    
    def send_email(self, to_email: str, subject: str, body: str) -> bool:
        """Send email"""
        
        if not self.sender_email or not self.sender_password:
            print("\n⚠️ Email not configured. Add EMAIL_ADDRESS and EMAIL_PASSWORD to .env")
            print("\n📧 Would have sent:\n")
            print(body)
            return False
        
        try:
            message = MIMEMultipart()
            message["From"] = self.sender_email
            message["To"] = to_email
            message["Subject"] = subject
            
            message.attach(MIMEText(body, "plain", "utf-8"))
            
            with smtplib.SMTP(self.smtp_server, self.smtp_port) as server:
                server.starttls()
                server.login(self.sender_email, self.sender_password)
                server.send_message(message)
            
            print(f"✅ Email sent to {to_email}")
            return True
            
        except Exception as e:
            print(f"❌ Email error: {e}")
            print("\n📧 Email content:\n")
            print(body)
            return False
    
    def send_flight_deals(self, to_email: str, origin: str, destination: str, flights: list) -> bool:
        """Send formatted flight deals"""
        
        subject = f"✈️ Flight Deals: {origin} → {destination}"
        
        body = f"""
╔══════════════════════════════════════════════════════════════╗
║                     ✈️ FLIGHT DEALS ✈️                       ║
╚══════════════════════════════════════════════════════════════╝

📍 From: {origin}
📍 To: {destination}
📅 Generated: {__import__('datetime').datetime.now().strftime('%Y-%m-%d %H:%M')}

{'═' * 60}

"""
        for i, flight in enumerate(flights[:5], 1):
            body += f"""
{i}. ✈️ {flight['airline']} - {flight['flight_number']}
   💰 Price: {flight['price']} {flight['currency']}
   🕐 Departure: {flight['departure']}
   🕐 Arrival: {flight['arrival']}
   📍 Source: {flight['source']}
   {'─' * 40}
"""

        if flights:
            best = flights[0]
            body += f"""

🏆 BEST DEAL: {best['airline']} at {best['price']} {best['currency']}

{'═' * 60}

🔗 Book directly with airline websites for best prices.

Generated by Travel Agent 🤖
"""
        
        return self.send_email(to_email, subject, body)